wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - 8081:80
  volumes:
    - ./wordpress/wp_html:/var/www/html
wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: examplepass
  volumes:
    - ./db:/var/lib/mysql
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8181:80
  environment:  
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: examplepass
