web:
  build: web/
  command: python counter.py
  ports: 
   - "80:5000"
  links:
   - redis

redis: 
  ports:
   - "6379:6379"
  #command: redis-server --appendonly yes
  build: redis/
  command: redis-server /config/redis.conf
  volumes:
   - /Users/star/Documents/docker/tmp_docker:/data
