version: '2'
services:
  httpd:
    container_name: httpd-container
    build: ./httpd
    ports:
      - "80:80"
    links: 
      - tomcat
  tomcat:
    container_name: tomcat-container
    build: ./tomcat
    expose:
      - "8009"
volumes:
  data: {}
